### ISSUE TITLE
Discuss introducing events

### ISSUE THREAD

**Issue by iamrecursion** [worldcoin/world-id-contracts#85]
Several relevant operations in the contracts do not emit events, making it difficult to monitor and review the contracts' behavior once deployed.

Operations that would benefit from emitting events include:
- `WorldIDIdentityManagerImplV1.initialize(...)`
- `WorldIDIdentityManagerImplV1.registerIdentities(...)`
- `WorldIDIdentityManagerImplV1.updateIdentities(...)`
- `WorldIDIdentityManagerImplV1.setStateBridge(...)`
- `WorldIDIdentityManagerImplV1.setSemaphoreVerifier(...)`
- `WorldIDIdentityManagerImplV1.setRootHistoryExpiry(...)`
- `WorldIDRouterImplV1.initialize(...)`
- `WorldIDRouterImplV1.addGroup(...)`
- `WorldIDRouterImplV1.updateGroup(...)`
- `WorldIDBridge._setRootHistoryExpiry(...)`
- `WorldIDAirdrop.claim(...)`

Emitting events for the relevant operations will enable users and blockchain monitoring systems to easily detect suspicious behaviors and ensure the correct functioning of the contracts.

However, we also originally _removed_ events from this contract (and others) in order to save on logging gas. We need to discuss what the correct course of action is here.

**Comment by recmo** [comment]
We can add these for administrative / uncommon transactions. I agree it is common practice and does have advantages around transaction analysis tooling.

However, logging each added identity in a batch would be very costly. So all rollups afaik just use calldata and expect a client to parse the calldata (instead of events).
